### ISSUE TITLE
mailer attachement

### ISSUE THREAD

**Issue by gagalago** [caxlsx/caxlsx_rails#12]
How can i use axls_rails within a mailer to have a attachement ?

in the mailer : 

``` ruby
class SocialSecretariatMailer < ActionMailer::Base
  def export
   attachments["Nouvelles entrées.xlsx"] = render xlsx: "/administration/contracts/social_secretariat", disposition: "attachment", filename: "nouvelles entrées - CESAM Nature - #{Date.today.to_s}.xlsx"
...
```

the error

```
Missing template social_secretariat_mailer/export with {:locale=>[:fr], :formats=[:html, :text, :js, :css, :ics, :csv, :png, :jpeg, :gif, :bmp, :tiff, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip, :xlsx], :handlers=>[:erb, :builder, :axlsx, :coffee, :haml, :prawn, :prawn_dsl]}. 
Searched in: (ActionView::MissingTemplate) * "/home/sigo/workspace/rcesam/app/views"
```

I feel that it is an error from the default rendered and not from the axls renderer.
Is it impossible to achieve this or I've made ​​a mistake ?

**Comment by mejiaro** [comment]
In case someone else is still having this problem with the syntax provided in the README, I got my template working using the following lines in the mailer:

```
xlsx = render_to_string formats: [:xlsx], template: "client/default/report", locals: {money: @money}
  	attachments['report.xlsx'] = {mime_type: Mime::XLSX, content: xlsx}
```

The template file is named report.xlsx.axlsx

**Comment by straydogstudio** [comment]
@mejiaro Just to be clear, you dropped the handlers specifier? Which version of Rails, Axlsx, axlsx_rails?

**Comment by mejiaro** [comment]
Yup, just removed the handlers. rails (4.2.5.1), axlsx (2.0.1), axlsx_rails (0.4.0)

**Comment by straydogstudio** [comment]
@mejiaro Thanks. I will update the docs at least.
