### ISSUE TITLE
Bar Chart inverted Axis

### ISSUE THREAD

**Issue by murgiuf** [caxlsx/caxlsx_rails#137]
Hi,

I'm ussing an example code to draw a Bar3DChart:

```
wb.add_worksheet(:name => "Bar Chart") do |sheet|
   sheet.add_row ["A Simple Bar Chart"]
   sheet.add_row ["First", "Second", "Third"]
   sheet.add_row [1, 2, 3]
   sheet.add_chart(Axlsx::Bar3DChart, :start_at => "A4", :end_at => "F17") do |chart|
     chart.add_series :data => sheet["A3:C3"], :labels => sheet["A2:C2"], :title => sheet["A1"]
     chart.valAxis.label_rotation = -45
     chart.catAxis.label_rotation = 45
     chart.d_lbls.d_lbl_pos = :outEnd
     chart.d_lbls.show_val = true    
     chart.catAxis.tick_lbl_pos = :none
   end
  end
```

The problem is that the chart has the axis inverted:

![inverted_axis](https://user-images.githubusercontent.com/38368722/72779691-c616f200-3bea-11ea-8b3b-45bca0a9b53b.png)

I'm sure this happened before in 2013: 

https://stackoverflow.com/questions/17201836/inverted-axis-in-axlsx-bar-chart/17321499

And it was fixed then. Right now my gem 'caxlsx_rails' is up-to-date but I'm still facing this issue.

Much thanks!
Freddy

**Comment by straydogstudio** [comment]
@murgiuf Have you found any solution on this? It might best be added to the Caxlsx gem, since this appears to be a caxlsx issue, and not caxlsx_rails. Also, which versions of calxsx/caxlsx_rails are in your lock file?

**Comment by straydogstudio** [comment]
Closing as not a caxlsx_rails issue.
