### ISSUE TITLE
How do you use Tabs?

### ISSUE THREAD

**Issue by RailsCod3rFuture** [caxlsx/caxlsx_rails#141]
Greetings, I am working with your gem for a project. I need to list Facility (Model) in each separate tab and list information that relates to that facility with another model called ChartRecord. It'll be pretty static in summing up values for the year/month for that particular facility. Does your gem support tabs?

**Comment by straydogstudio** [comment]
@RailsCod3rFuture If you mean sheets, which are displayed as tabs along the bottom in Excel, then yes. You create each sheet for a given worksheet. There is plenty of documentation in the [readme for caxlsx](https://github.com/caxlsx/caxlsx). Please clarify if this doesn't answer your question.
