### ISSUE TITLE
iso-8601 dates are strange floating points?

### ISSUE THREAD

**Issue by patrick99e99** [caxlsx/caxlsx_rails#144]
if I put a value like "2014-01-17T00:44:28.000Z" in a column, in excel/numbers it shows up as a number like: 44069.032777581

How can I make caxlsx keep it as the original iso string?

**Comment by straydogstudio** [comment]
@patrick99e99 You'll get better responses if you create this issue on the caxlsx gem, since it is really essential to that gem, not the rails adapter. Please recreate there.

**Comment by patrick99e99** [comment]
ok thanks.
