### ISSUE TITLE
File encrypted password in xlsx

### ISSUE THREAD

**Issue by MaeCess** [caxlsx/caxlsx_rails#145]
Currently, I'm using gem caxlsx for generating my excel'

is there anyone try to file a password before generating the excel file?

the goal here. is the user click the button then some text will pop up to type the password of excel. then the system will generate the excel automatically download in the browser.

**Comment by straydogstudio** [comment]
@MaeCess Sorry for the lack of response here. Did you get a solution for your problem? You would just have to have a method to request the password for the file before you generate it, sending it as a parameter.

**Comment by tlkiong** [comment]
@straydogstudio And what method would that be?

**Comment by straydogstudio** [comment]
@tlkiong I'm closing this as it isn't really an issue with this gem. You'll need to create a way inside Rails to accept input from the user, whether a form or a JavaScript popup, and send that password with your request to the server. Then use that password while creating the xlsx file.
