### ISSUE TITLE
secure-spreadsheet 

### ISSUE THREAD

**Issue by MaeCess** [caxlsx/caxlsx_rails#146]
as per documentation said there is call spreadsheet protection which will lock the specific sheet

anyone tried to lock the whole excel file?

**Comment by straydogstudio** [comment]
@MaeCess these kind of requests, which are more specific to Caxlsx, will do better on the Caxlsx gem, since they are usage related to that gem. Or you can try the slack channel. See the readme for Caxlsx to find the Slack channel link.
