### ISSUE TITLE
no way to reload page after xlsx file is generated

### ISSUE THREAD

**Issue by RohitVenturit** [caxlsx/caxlsx_rails#147]
After xlsx file is genereated, there is no way to reload page. How do we relaod page after process is completed?

**Comment by straydogstudio** [comment]
I assume you mean by reloading refreshing the browser and getting the results more quickly? That depends on what you are doing, e.g. a post/get request. It should always respond the same to the same request. 

You might also mean caching results. caxlsx_rails is a thin layer to calling caxlsx and generating a spreadsheet. It doesn't provide any caching of results in between. You would have to do that yourself, saving the results of the process and making it available outside the given request. You could probably even export to file inside the template itself. But managing and reserving the results would take more work. Unfortunately I don't think we have any examples. You could put this out on the Slack channel and see if anyone has any suggestions. There is a link to join Slack on the readme.
