### ISSUE TITLE
Is there anyway to render xlsx package object without template?

### ISSUE THREAD

**Issue by xyingsoft** [caxlsx/caxlsx_rails#150]

**Comment by straydogstudio** [comment]
Sure. You can run the Caxlsx code directly in the controller, or in a model, or in some other location. Then take the final object and render it to a string and return it in the controller. Something like this in the end:

```
p = Axlsx::Package.new
//do stuff here to create your workbook
send_data p.to_stream.string, filename: "file_name.xlsx", type: Mime::XLSX, disposition: 'attachment'
```

You can also join the Slack channel for caxlsx and ask questions there. See the Readme for Caxlsx.

**Comment by xyingsoft** [comment]
Great I will try @straydogstudio
