### ISSUE TITLE
Align caxlsx dependency to support last version (3.1)

### ISSUE THREAD

**Issue by stonefield** [caxlsx/caxlsx_rails#151]
caxlsx has new features. I believe these are not in conflict with existing implementation for rails. Please update dependency.
See new features added: [Recent changelog](https://github.com/caxlsx/caxlsx/commit/aa361aa0518f785f2be32bb06c2621db631d17eb)

**Comment by straydogstudio** [comment]
Thanks @stonefield. The dependencies on caxlsx_rails are pretty loose. It only specifies ActionPack >= 3.1, and caxlsx >= 3.0. Are you thinking it should specify caxlsx >= 3.1 from now on?

**Comment by stonefield** [comment]
Looks like it does not matter. But there are significant fixes in the latest version of caxlsx, so yes >= 3.1

**Comment by stonefield** [comment]
I upgraded rails today, and there was no conflict. So I think my assumptions were wrong. Better leave it as is. Closing.

**Comment by straydogstudio** [comment]
@stonefield Thanks.
