### ISSUE TITLE
Question: Get formula value

### ISSUE THREAD

**Issue by newfylox** [caxlsx/caxlsx_rails#157]
Hi guys, quick question,

is there a way to get formula cell's value? If my cell is `=SUM(A1:B1)`,  can I call this cell and get its real value and not the formula string?

Thanks

**Comment by straydogstudio** [comment]
@newfylox You'll want to post that on the Slack channel (preferably), or put it as an issue on the Caxlsx gem. 

See the README here: https://github.com/caxlsx/caxlsx
