### ISSUE TITLE
如何将我的附件( attachment ) 写入到xlsx表格当中,注意：不是图片

### ISSUE THREAD

**Issue by Jgl520** [caxlsx/caxlsx_rails#168]

**Comment by straydogstudio** [comment]
We will need this in english if it is a valid issue.

**Comment by straydogstudio** [comment]
If Google translate is correct, you are asking about attaching a file to a spreadsheet, but not an image. That would be a caxlsx issue specifically, not a caxlsx_rails issue. I would advise you join the Slack group and ask the question there under the caxlsx channel. Or, use stackoverflow.com to ask the question. 

See the readme for the link to the Slack channel: https://github.com/caxlsx/caxlsx#notice-community-axlsx-organization
