### ISSUE TITLE
Excel Displays Warning Modal When Using `add_hyperlink` Function

### ISSUE THREAD

**Issue by erados** [caxlsx/caxlsx_rails#169]
Hello there.

I'm encountering an issue with the hyperlink function in caxlsx that I hope you can help me with.

Up until now, my experience with caxlsx has been quite smooth. However, I've hit a roadblock after introducing hyperlinks to my Excel file using the `ws.add_hyperlink(location: url, ref: target_cell)` function. The problem arises when I attempt to open the file, as I'm presented with an unexpected modal. Your guidance in resolving this matter would be greatly appreciated.

<img width="292" alt="Screenshot 2023-08-29 at 12 38 08 PM" src="https://github.com/caxlsx/caxlsx_rails/assets/19205043/3868e46a-0ce3-4a29-b34f-ed333f0c3116" alt="We found a problem with some content in '3255_company_20230829122105.xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes.">

Additionally, I found that Excel is generating this specific file as well.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
	<logFileName>Repair Result to 3255_company_202308291221051.xml</logFileName>
	<summary>Errors were detected in file '/Users/songmyeong-u/Downloads/3255_company_20230829122105.xlsx'</summary>
	<removedRecords summary="Following is a list of removed records:">
		<removedRecord>Removed Records: Formula from /xl/worksheets/sheet1.xml part</removedRecord>
	</removedRecords>
</recoveryLog>
```

Moreover, when using Numbers, the issue persists in a similar manner.

<img width="630" alt="Screenshot 2023-08-29 at 12 46 28 PM" src="https://github.com/caxlsx/caxlsx_rails/assets/19205043/76b06600-62e7-4ead-be6d-7fa75d384413">

However, it's worth noting that despite the modal appearing, the hyperlinks are still functional once the file is opened. 
I would like to extend my appreciation for your efforts in maintaining this valuable tool.

**Comment by straydogstudio** [comment]
Hi @erados. Would you recreate this issue under the caxlsx repo? This doesn’t look like a caxlsx_rails issue. Thanks for submitting.
