### ISSUE TITLE
unable to Open file with office 360

### ISSUE THREAD

**Issue by prosenjit98** [caxlsx/caxlsx_rails#171]

**Comment by kiskoza** [comment]
Could you provide any details or steps to reproduce? Does it seem to be a bug in the rails integration (e.g.: wrong mimetype given back from the server) or a bug within the caxlsx gem itself? Could you provide the related gem versions used in your app?

**Comment by prosenjit98** [comment]
using recent version I have generated xlsx file but this file is not opening on Office 360 at all.

**Comment by straydogstudio** [comment]
@prosenjit98  We would need some specific source code, a way to repeat the error. Are you saying anything causes an error, even a blank worksheet?

What gem versions for caxlsx (and other relevant gems) are in your lock file?
