### ISSUE TITLE
Is there a way to print a single sheet

### ISSUE THREAD

**Issue by newfylox** [caxlsx/caxlsx_rails#177]
I was wondering if it's possible to show a single sheet when generating the file to xlsx format?

Like I have 2 sheets (the second one is for calculating) but would like to only output the first sheet.

Thanks

**Comment by kiskoza** [comment]
It is a question about caxlsx itself and the same was asked on the caxlsx repo https://github.com/caxlsx/caxlsx/issues/373, so I'm closing this one
