### ISSUE TITLE
Tag for Rails 7

### ISSUE THREAD

**Issue by vincentchong** [caxlsx/caxlsx_rails#178]
Hi, is there any plan to come out a new tag for Rails 7?
The Tag v0.6.3 is up to Rails 6 only.

**Comment by straydogstudio** [comment]
We just haven't gotten around to adding the tag. It is tested on Rails 7.0 and 7.1.

**Comment by vincentchong** [comment]
Possible to add a new tag base on master branch?

**Comment by straydogstudio** [comment]
@vincentchong where are you seeing 0.6.3 is only for Rails 6? I did see the Readme only said to Rails 6, but it has been tested up to 7 for a while. I updated the Readme.

**Comment by vincentcvincent** [comment]
Hi @straydogstudio , in 0.6.3, caxlsx_rails/Gemfile, only up to using Rails 6.0, and the last update was 9 March 2022.

The gem still works, but using older Rails and it's dependencies might not include the security patch from some of the gems.

Last but not least, the master branch is using a different folder structure which I think is a lot better.

Really appreciate if releasing a new tag from the master branch.

Thank you for the hard work.

**Comment by straydogstudio** [comment]
I'll get to it relatively soon. I'd like to fix the testing suite before I release it. Some of the testing is failing.

**Comment by kiskoza** [comment]
I fixed the CI, we should be able to release a new version if you like. I'd suggest releasing v0.6.4 as we don't really have any changes apart from stabilizing test suites and adding new versions to the test matrix

**Comment by straydogstudio** [comment]
Thank you so much @kiskoza !! I'll get it released today.

**Comment by straydogstudio** [comment]
0.6.4 tagged and released
