### ISSUE TITLE
undefined method `reopen' for "streamed":String

### ISSUE THREAD

**Issue by lremes** [caxlsx/caxlsx_rails#18]
I'm using axlsx rails 0.1.5 with rvm, ruby-2.1.0 and rails 4.0.4, 

I get the following exception in my view, and it seems to be an axlsx problem.
The line number in the error is invalid as the view file itself is only 25 lines long.

```
An ActionView::Template::Error occurred in competences#certificates_to_excel:

  undefined method `reopen' for "streamed":String
  app/views/cb/competences/certificates_to_excel.xlsx.axlsx:27:in `_app_views_cb_competences_certificates_to_excel_xlsx_axlsx___1718042271781105460_75871920'
```

When I grep the code, the only code where I find mentions of "reopen" or "streamed" are in rubyzip code and axlsx/axlsx_rails.

The problem is that I'm unable to duplicate this in my development environment. It only occurs in production, where the ruby and gem versions are the same.

I would like to use newer version of axlsx, but for some reason the gem always uses axlsx-1.3.6. How can I use the latest 2.0.1 version?

**Comment by maniempire** [comment]
Thanks and this solution works and saved me a lot of time.

**Comment by workgena** [comment]
Lock: gem 'axlsx', '2.0.1'
This helped me too.

**Comment by Harpalsinh** [comment]
I am using zip zip gem,
having the same issue.

**Comment by straydogstudio** [comment]
@Harpalsinh What versions of Axlsx and zip are in your Gemfile.lock?

**Comment by mariowise** [comment]
@Harpalsinh: I've perform some `bundle update` and then the final `Gemfile` that worked for me was this

	# EXCEL
	gem 'roo'
	gem 'iconv'
	gem 'rubyzip'
	gem 'zip-zip'
	gem 'axlsx', '~> 2.0'
	gem 'acts_as_xlsx'
	gem 'axlsx_rails'

Regards

**Comment by harpalsinhrana** [comment]
I was having trouble initially while using latest gem versions.
so I have following versions now and that serves perfect dependency, Won't raise any error.
* axlsx (2.0.0)
 * axlsx_rails (0.1.5)
* roo (1.13.2) # Use roo for file uploads. and this version needs 
* rubyzip (0.9.9) # version more then this will rails  error.

**Comment by straydogstudio** [comment]
@Harpalsinh @harpalsinhrana @mariowise @workgena 

If you look at the [change log for Axlsx](https://github.com/randym/axlsx#change-log), Axlsx 2.0.0 pinned rubyzip at 0.9.9 for those who needed it. Axlsx 2.0.1 and up use rubyzip 1.x.x and above. 

As of version 0.2.0 axlsx_rails requires Axlsx 2.0.1 or above. Changing to axlsx_rails 0.2.0 or above (0.4.0 is the latest version) should not cause any issues; there are a few breaking changes for borderline situations. Most of the changes from 1.5 to 2.0 had to do with Rails 4 changes. If you are using Rails 4.2, you will want axlsx_rails 0.4.0 or above. If you are still in Rails 3, axlsx_rails 1.5 should work just fine. 

I will improve the Readme . I don't think it is clear enough.

**Comment by harpalsinhrana** [comment]
Thanks noel.

On Tue, Aug 18, 2015 at 8:09 PM, Noel Peden <notifications@github.com>
wrote:

> @Harpalsinh <https://github.com/Harpalsinh> @harpalsinhrana
> <https://github.com/harpalsinhrana> @mariowise
> <https://github.com/mariowise> @workgena <https://github.com/workgena>
>
> If you look at the change log for Axlsx
> <https://github.com/randym/axlsx#change-log>, Axlsx 2.0.0 pinned rubyzip
> at 0.9.9 for those who needed it. Axlsx 2.0.1 and up use rubyzip 1.x.x and
> above.
>
> As of version 0.2.0 axlsx_rails requires Axlsx 2.0.1 or above. Changing to
> axlsx_rails 0.2.0 or above (0.4.0 is the latest version) should not cause
> any issues; there are a few breaking changes for borderline situations.
> Most of the changes from 1.5 to 2.0 had to do with Rails 4 changes. If you
> are using Rails 4.2, you will want axlsx_rails 0.4.0 or above. If you are
> still in Rails 3, axlsx_rails 1.5 should work just fine.
>
> I will improve the Readme . I don't think it is clear enough.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/straydogstudio/axlsx_rails/issues/18#issuecomment-132234648>
> .
>



-- 
Thanks & Best Regards
Harpalsinh Rana
Ahmedabad

**Comment by zerocool4u2** [comment]
@straydogstudio thanks man, 
```ruby
gem 'axlsx_rails', '>=0.4.0'
```
fix my issues, before i have problems with webrick crashing, to fix this i need to add gems zip/zip and axlsx, your solution works like a charm just with that gem all dependencies issues were fixed, really really appreciate(nearly 5 hours looking for info about this), regards!!

*Relevant dependencies and gems*
```ruby
gem 'rails', '4.2.4'
gem 'activeadmin', github: 'activeadmin' 
gem 'roo'
```
**PD:** *for everyone there looking to fix this in activeadmin, you will encounter a problem before this about unknown respond_to type(no documentation about it either, at least not on the right direction )*
```ruby
	controller do	
		respond_to :xlsx, only: :index
	end
```
*will fixed it(don't forget to add it to the __active_admin.rb__ initializer), then you will have the dependencies issues that the axlsx_rails version above will fix, just follow the guide on axlsx_rails's github site then.*

**Comment by cathyzoller** [comment]
I realize this is a closed issue, but just want to report my findings as of Dec. 8, 2015.
roo gem depends on rubyzip ~> 1.1 <= 2.0
axlsx 2.0.1 depends on rubyzip 1.0.0
However, towards the bottom of this issue from March 14,  https://github.com/randym/axlsx/issues/328 a pre-release of 2.1 was released.  Using  ```gem 'axlsx', '2.1.0.pre'``` and ```gem axlsx_rails >=0.4``` solves the compatibility conflict.

**Comment by straydogstudio** [comment]
@cathyzoller Thanks for the findings!

**Comment by vinhboy** [comment]
@cathyzoller Thanks for the fix. This worked for problems in @straydogstudio branch of acts_as_xlsx as well. Seems like Roo gem causes problems.

**Comment by cathyzoller** [comment]
Your welcome.

On Wed, Dec 16, 2015 at 1:39 PM, Vinh Pham <notifications@github.com> wrote:

> @cathyzoller <https://github.com/cathyzoller> Thanks for the fix. This
> worked for problems in @straydogstudio <https://github.com/straydogstudio>
> branch of acts_as_xlsx as well. Seems like Roo gem causes problems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/straydogstudio/axlsx_rails/issues/18#issuecomment-165232278>
> .
>



-- 
Catherine Zoller
cathyzoller@gmail.com
815-980-4183

**Comment by maaris** [comment]
@cathyzoller tnx, worked for me also!

**Comment by straydogstudio** [comment]
I've added a note about this find at the top of the Readme.

**Comment by Dimcha** [comment]
Thanks @cathyzoller , saved time for me!

**Comment by slim1979** [comment]
good day for everyone.
this combination worked fine:
```
gem 'axlsx', '2.0.0'
gem 'axlsx_rails', '0.1.5'
gem 'rubyzip', '0.9.9'
```

**Comment by shamane** [comment]
or 

```
gem 'axlsx', git: 'https://github.com/randym/axlsx.git', ref: 'c8ac844'
gem 'axlsx_rails'
```

as described there https://medium.com/@JasonCodes/ruby-on-rails-exporting-data-to-excel-b3b204281085

**Comment by tomalla5120x** [comment]
Unfortunately I have encountered this very problem as well. The discussion here gave me some hints on where to look but it lacked a more detailed analysis of the problem and left me rather unsatisfied.

The source of the problem comes from rubyzip gem which at some point changed its API. The version rubyzip-1.1.1 introduced the changes which in turn broke the axlsx gem ([here is the offending change](https://github.com/rubyzip/rubyzip/commit/c7f0b17abffd19ce2d783e1b9f84cac5fde8c86d#diff-4bd55480ed2eadb3912ec6b8491cb33afbb35ac96238175b113e3ff4aad234fcL29)). The last version containing the "old" API is rubyzip-1.1.0.

Now axlsx gem at some point fixed the error. It did so in version axlsx-2.1.0.pre and since then it references the new rubyzip API. The last version referencing the old API is axlsx-2.0.1.

So if you have this error you have two options. Either upgrade axlsx gem to version 2.1.0.pre (or greater) or downgrade the rubyzip gem to the version 1.1.0 (or lower).

Unfortunately for me I couldn't do either because they hopelessly broke other dependencies either way and the dependency hell ensued. So I stayed with axlsx-1.3.6 (referencing the rubyzip "old" API) and **locked** this gem version in my Gemfile, rubyzip-2.3.0 (which contained the "new" API) and rolled up the hotfix myself. Since I've been using Rails 4.2.0, I've created the following initializer overwriting the to_stream method:

```ruby
class Axlsx::Package
  def to_stream(confirm_valid=false)
    return false unless !confirm_valid || self.validate.empty?
    # the fix replaced "streamed" with StringIO.new
    zip = write_parts(Zip::ZipOutputStream.new(StringIO.new, true))
    stream = zip.close_buffer
    stream.rewind
    stream
  end
end
```

This solution finally fixed my problem for good.
