### ISSUE TITLE
Reduce supported rubies and rails versions?

### ISSUE THREAD

**Issue by timdiggins** [caxlsx/caxlsx_rails#184]
Thanks for the work on this great gem. 

I was wondering if you really want to commit to so many EOL'd rails and Ruby versions and if you'd be open to a PR reducing them?

Would make it easier to contribute and keep tests green.

**Comment by straydogstudio** [comment]
Certainly. I am incredibly busy, and welcome PRs. Just be sure the PR provides justification in the description. 

And you are certainly welcome
