### ISSUE TITLE
wrong number of arguments (2 for 1)

### ISSUE THREAD

**Issue by tucano** [caxlsx/caxlsx_rails#21]
Hi, I am following the basic tutorial. In my controller I have:

def index
  @collaborators = Collaborator.all
  respond_to do |format|
        format.html # index.html.erb
        format.xlsx
  end
end

And I get:

wrong number of arguments (2 for 1) from the template (index.xlsx.axlsx)

Any more info I can give you?

**Comment by vikashvikram** [comment]
I did the same i.e.
gem 'axlsx', '~> 2.0.1'
gem 'axlsx_rails'

and my app does not give any error. In the log, I can see following
Rendered admin/download/users.xlsx.axlsx (43.6ms)
Completed 200 OK in 100ms (Views: 80.2ms | ActiveRecord: 1.1ms)

but when I try to open the file, It says file is corrupt and cannot be opened. I just could not found any trace of any error to give me a clue about what might have gone wrong. Any help??

Thanks

**Comment by straydogstudio** [comment]
Does it work with a lower version of axlsx_rails? Is it corrupt when you just use the latest Axlsx and a rails script to create the file? 

We have another issue recently posted with the same issue. No errors, but the spreadsheet can't be opened: https://github.com/straydogstudio/axlsx_rails/issues/40

**Comment by vikashvikram** [comment]
I tried 0.3.0 also instead for 0.4.0 but same issue. I am using Rails 4.1.6, ruby 2.2.1, Mac OS X Yosemite.

**Comment by straydogstudio** [comment]
@vikashvikram  What version of rubyzip do you have? we've got some kind of gem interaction that is causing a problem I think.

**Comment by straydogstudio** [comment]
@vikashvikram You might try fixing rubyzip at 1.1.0.

**Comment by samiljin** [comment]
Having the same issue as @vikashvikram. 0.3.0 and 0.4.0 gives the same result for me. Cannot open the generated files. Rails 4.2.4, Ruby 2.2.3 and OS X El Capitan
